call pathogen#infect()

set nocompatible
set encoding=utf-8
set mouse=a
filetype plugin indent on


"" Whitespace
set nowrap
set tabstop=4 shiftwidth=4 et
set softtabstop=4
set expandtab
set backspace=indent,eol,start
set autoindent
set autoread 
set clipboard=unnamed
"au BufRead,BufNewFile *.py,*.pyw,*.php set textwidth=79

"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

"" Leader key
let mapleader = ","

"" Disable cursor keys
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

"" Disable cursor keys in insert mode
inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>

noremap <leader><space> :noh<cr>:call clearmatches()<cr>
"let g:ctrlp_map = '<leader>p'
nmap <leader>p :CtrlP<CR>
nmap <leader>P :CtrlPClearCache<CR>:CtrlP<CR>

nmap <leader>t :TagbarToggle<CR>

nnoremap <leader>a :Ack!<space>
"inoremap <Nul> <C-x><C-o>

noremap H ^
noremap L $

nmap <leader>d :NERDTreeToggle<CR>
nmap <leader>f :NERDTreeFind<CR>


"" Backup & tmp files
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp

" Omni-complete 
"let $Tlist_Ctags_Cmd='/usr/local/bin/ctags'
"let g:clang_user_options='|| exit 0'
let g:jedi#auto_initialization = 0
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType php set omnifunc=phpcomplete#CompletePHP

"" Interface
syntax enable
set showcmd
set statusline+=%#warningmsg#
set noerrorbells
set t_Co=256
let g:Powerline_symbols = 'fancy'
"let g:airline_powerline_fonts = 1

"colorscheme solarized
"let g:solarized_termtrans=0
"let g:solarized_termcolors=256
"let g:solarized_contrast="high"
"let g:solarized_visibility="high"
"colorscheme molokai 
"colorscheme badwolf
colorscheme jellybeans 

"set guitablabel=[%N]\ %M\ %t
set guitablabel=%N/\ %t\ %M
"set guitablabel=[%N]\ %M\ %{ShortTabLabel()} 
set ruler
set laststatus=2
set lazyredraw
"set showmatch
set scrolloff=10
set sidescrolloff=10
set statusline=%F%m%r%h%w[%L][%{&ff}]%y[%p%%][%04l,%04v]
set cursorline

set wildignore=*.bak,*.pyc,*.swp
set wildmenu
set wildmode=longest,list,full


"autocmd FileType html,htmldjango,jinjahtml,eruby,mako,phtml let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako,phtml,tpl source ~/.vim/bundle/closetag/plugin/closetag.vim

au BufRead,BufNewFile *.scss set filetype=scss
au BufRead,BufNewFile *.txt,*.tex set wrap linebreak nolist textwidth=0 wrapmargin=0

"" Django
noremap _dt :set ft=htmldjango<CR>
nnoremap _pd :set ft=python.django<CR>
au BufNewFile,BufRead admin.py     setlocal filetype=python.django
au BufNewFile,BufRead urls.py      setlocal filetype=python.django
au BufNewFile,BufRead models.py    setlocal filetype=python.django
au BufNewFile,BufRead views.py     setlocal filetype=python.django
au BufNewFile,BufRead settings.py  setlocal filetype=python.django
au BufNewFile,BufRead forms.py     setlocal filetype=python.django

"" Syntastic
let g:syntastic_enable_signs = 1
let g:syntastic_check_on_open = 1
let g:syntastic_disabled_filetypes = ['html', 'rst']
let g:syntastic_stl_format = '[%E{%e Errors}%B{, }%W{%w Warnings}]'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1
