call pathogen#infect()

set showcmd
set statusline+=%#warningmsg#
set nocompatible
syntax enable
set encoding=utf-8
set showcmd
filetype plugin indent on

set showcmd
set showcmd
set showcmd
set showcmd

"" Whitespace
set nowrap
set tabstop=4 shiftwidth=4
set softtabstop=4
set expandtab
set backspace=indent,eol,start
set autoindent
set textwidth=79
au BufRead,BufNewFile *.py,*.pyw,*.php set textwidth=79

"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

"" Leader key
let mapleader = ","

"" Disable cursor keys
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

"" Disable cursor keys in insert mode
inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>

noremap <leader><space> :noh<cr>:call clearmatches()<cr>
let g:ctrlp_map = '<leader>p'
nnoremap <leader>a :Ack!<space>


"" Backup & tmp files
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp

" Autocomplete
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType php set omnifunc=phpcomplete#CompletePHP

"" Interface
let g:Powerline_symbols = 'fancy'
set noerrorbells
set t_Co=256
set background=dark 
let g:solarized_termtrans=0
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized
set guitablabel=[%N]\ %t
set ruler
set laststatus=2
set lazyredraw
"set showmatch
set scrolloff=10
set sidescrolloff=10
set statusline=%F%m%r%h%w[%L][%{&ff}]%y[%p%%][%04l,%04v]
set cursorline

set wildignore=*.bak,*.pyc,*.swp
set wildmenu
set wildmode=list:longest

"autocmd FileType html,htmldjango,jinjahtml,eruby,mako,phtml let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako,phtml source ~/.vim/bundle/closetag/plugin/closetag.vim

au BufRead,BufNewFile *.scss set filetype=scss

"" Django
noremap _dt :set ft=htmldjango<CR>
nnoremap _pd :set ft=python.django<CR>
au BufNewFile,BufRead admin.py     setlocal filetype=python.django
au BufNewFile,BufRead urls.py      setlocal filetype=python.django
au BufNewFile,BufRead models.py    setlocal filetype=python.django
au BufNewFile,BufRead views.py     setlocal filetype=python.django
au BufNewFile,BufRead settings.py  setlocal filetype=python.django
au BufNewFile,BufRead forms.py     setlocal filetype=python.django

"" Syntastic
let g:syntastic_enable_signs = 1
let g:syntastic_check_on_open = 1
let g:syntastic_disabled_filetypes = ['html', 'rst']
let g:syntastic_stl_format = '[%E{%e Errors}%B{, }%W{%w Warnings}]'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
"let g:syntastic_jsl_conf = '$HOME/.vim/jsl.conf'
"

